### ISSUE TITLE
get manifest data

### ISSUE THREAD

**Issue by krishnaglodha** [geobeyond/geoserverx#71]
when we hit `localhost:8080/geoserver/rest/about/manifest.json` we get data as file  [manifest (2).json](https://github.com/user-attachments/files/17789204/manifest.2.json), for the pydantic, it is difficult to gauge
what might be the dictionary content, of each resource, should we just use dict for it ?

**Comment by ricardogsilva** [comment]
Looking at the manifest (here is a formatted snippet):

```yaml
{
  "about": {
    "resource": [
      # other resources omitted for brevity
      {
        "@name": "GeographicLib-Java-1.49",
        "Archiver-Version": "Plexus Archiver",
        "Manifest-Version": 1,
        "Created-By": "Apache Maven 3.3.9",
        "Built-By": "ckarney",
        "Build-Jdk": "1.8.0_144"
      },
      {
        "@name": "JavaAPIforKml-2.2.0",
        "Archiver-Version": "Plexus Archiver",
        "Manifest-Version": 1,
        "Created-By": "Apache Maven",
        "Built-By": "flori",
        "Build-Jdk": "1.6.0_15"
      },
      {
        "@name": "aircompressor-0.27",
        "Implementation-Title": "aircompressor",
        "Specification-Version": 0.27,
        "Build-Time": "2024-05-20T14:15:10-0700",
        "Implementation-Version": 0.27,
        "Manifest-Version": 1,
        "Created-By": "Maven Jar Plugin 3.2.0",
        "Build-Jdk-Spec": 21,
        "Specification-Title": "aircompressor",
        "Git-Commit-Id": "e139a31be059855a5a70f6994a4ecaa0adbbea7a"
      }
    ]
  }
}

```

 it seems to be a representation of the standard Java manifest files:

- https://docs.oracle.com/javase/8/docs/technotes/guides/jar/jar.html#JAR_Manifest
- https://docs.oracle.com/javase/tutorial/deployment/jar/manifestindex.html
  
Therefore these do have a strict schema that we can use to build our pydantic models.

Would we want to do this though?

I think we should keep only the relevant bits of this payload - and at the moment I'm not sure what those would be. Perhaps we can start by keeping only the `@name` property (as this seems to be a combination of the `Implementation-Title` and `Implementation-Version` properties).

With this in mind, perhaps geoserverx would simply return a list of strings, where each string would be the `@name` property of the original response payload.
